### ISSUE TITLE
Fazer a prototipagem da página de busca

### ISSUE THREAD

**Issue by gustavo-p0** [START-DB-2023/desafio_db_grupo_03#13]
Definir a palheta de cores e o design geral do site.

**Comment by AurorinhaBoreal** [comment]
Prototipagem Inicial da Tela de Busca:

![Image](https://github.com/START-DB-2023/desafio_db_grupo_03/assets/124530477/a0c7b7d4-06d4-4fdc-a962-e6a8f836505c)

Essa prototipagem inicial define a estrutura da página de pesquisa e como os Cards de cada ponto de coleta será apresentado

**Comment by AurorinhaBoreal** [comment]
Prototipagem Final da Página de Busca:
![Image](https://github.com/START-DB-2023/desafio_db_grupo_03/assets/124530477/a060032e-cc88-4162-a6dd-8f1242a2ac1e)

Essa página permitirá a busca dos pontos de coleta por nome, materiais coletados e cidade.

Conforme o avanço do projeto e a necessidade, outras páginas serão prototipadas.
