### ISSUE TITLE
[RF 001.6] Desenvolver o formulário para cadastro de Instituições Administrativas

### ISSUE THREAD

**Issue by gustavo-p0** [START-DB-2023/desafio_db_grupo_03#14]
Desenvolver a página Web ou componente responsavel pela visualização do formulário de cadastro de insituições administrativas.

**Comment by AurorinhaBoreal** [comment]
Assim como o Forms Material, esse forms tem os campos da entidade de Instituições Administrativas presentes no Banco de Dados

![Image](https://github.com/START-DB-2023/desafio_db_grupo_03/assets/124530477/402ba204-75f0-4850-b8c5-e7462d93bfd3)

Possui o mesmo design do formulário anterior justamente para manter a consistência e agradar o usuário
