### ISSUE TITLE
[RF 001.7] Vincular Formulário com Entidade Instituições Administrativas

### ISSUE THREAD

**Issue by gustavo-p0** [START-DB-2023/desafio_db_grupo_03#17]
Vincular a página Web do Formulário com a Entidade Material no Banco de Dados

**Comment by AurorinhaBoreal** [comment]
Foram criadas querys para fazer o vinculo com o formulário e a API, que consequentemente fazia conexão com a entidade no Banco PostgreSQL


![Image](https://github.com/START-DB-2023/desafio_db_grupo_03/assets/124530477/334b9232-193c-4a04-867f-3f3c7a675761)


![Image](https://github.com/START-DB-2023/desafio_db_grupo_03/assets/124530477/e61f14e6-21fc-4ec1-9895-75f4f87e2260)
