### ISSUE TITLE
[RF-011] Permitir a visualização das instituições administradoras em um cliente web

### ISSUE THREAD

**Issue by gustavo-p0** [START-DB-2023/desafio_db_grupo_03#26]
Criação da tela de visualização das instituições administradoras

**Comment by AurorinhaBoreal** [comment]
Foi criada a tela de visualização das instituições administrativas


![Image](https://github.com/START-DB-2023/desafio_db_grupo_03/assets/124530477/8b42ca19-ba2f-4d8f-838b-72d29eba40dc)

É feita a busca no Banco de Dados e as Instituições são mostradas da página /administradoras
